# docker-compose.yaml
version: '3.8'

networks:
  tanuki_network:
    driver: bridge

services:
  tanuki-angular:
    container_name: tanuki-angular-compose
    build:
      context: ../.
      dockerfile: docker/angular/Dockerfile
    networks:
      - tanuki_network
    expose:
      - 80
      - 443
    ports:
      - "80:80"
      - "443:443"
    environment:
      - NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx
      - NGINX_HOST=localhost
      - NGINX_PORT=80
      - PORT=80


  tanuki-socket:
    container_name: tanuki-socket-compose
    build:
      context: ../.
      dockerfile: docker/node/Dockerfile
    networks:
      - tanuki_network
    expose:
      - 8000
    ports:
      - "8000:8000"
    environment:
      NODE_ENV: development
      PORT: 8000
