name: Angular and containerization

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Cache node modules
      id: cache-nodemodules
      uses: actions/cache@v3
      env:
        cache-name: cache-node-modules
      with:
        # caching node_modules
        path: node_modules
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build
      run: npm run build -- --configuration production --base-href='https://berghuispeter.github.io/project-tanuki/'
    
    - name: Archive build
      if: success()
      uses: actions/upload-artifact@v4.3.1
      with:
        name: deploy_dist
        path: dist

  containerization:
    needs: build
    runs-on: ubuntu-latest
    steps:
    
    # - name: Checkout code
    #   uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Download build
      uses: actions/download-artifact@v4.1.2
      with:
        name: deploy_dist
        path: dist
      
    - name: Docker Login
      uses: docker/login-action@v3.0.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: test
      run: pwd && ls -lR

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        file: ./docker/angular/Dockerfile
        push: false
        tags: ${{ secrets.DOCKER_USERNAME }}/my-dev-ops-test:latest
        
        
    # - name: Build Docker image angular
    #   run: docker build -t tinea/my-dev-ops-test:latest docker/angular/.
      
    # - name: Push Docker image angular
    #   run: docker push tinea/my-dev-ops-test:latest
