on:
  push:
    branches: [ develop, master ]

jobs:
  dev:
    name: deploy to dev environment
    if: ${{ github.ref == 'refs/heads/develop' || github.base_ref == 'develop' }}
    uses: ./.github/workflows/_deployment.yaml
    permissions:
      id-token: write
      contents: read
    with:
      environment: dev
      ref: ${{ github.sha }}
    secrets: inherit
  prod:
    name: deploy to prod environment
    if: ${{ github.ref == 'refs/heads/master' || github.base_ref == 'master' }}
    uses: ./.github/workflows/_deployment.yaml
    permissions:
      id-token: write
      contents: read
    with:
      environment: prod
      ref: ${{ github.sha }}
    secrets: inherit
