name: Tanuki-workflow

on:
  push:
    branches: [ develop, master ]

jobs:
  dev:
    name: deploy to dev
    if: ${{ github.ref == 'refs/heads/develop' || github.base_ref == 'develop' }}
    uses: ./.github/workflows/_deployment.yml
    secrets: inherit
    with:
      environment: dev
  prod:
    name: deploy to prod
    if: ${{ github.ref == 'refs/heads/master' || github.base_ref == 'master' }}
    uses: ./.github/workflows/_deployment.yml
    secrets: inherit
    with:
      environment: prod
